# データベース接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/sampledb_task
spring.datasource.username=hogeuser
spring.datasource.password=hoge
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate（DB構造の自動操作）を停止する設定
# すでにpgAdminでテーブルを作成済みのため、"none" にしてエラーを防ぎます
spring.jpa.hibernate.ddl-auto=none

# SQLログの表示設定
spring.jpa.show-sql=true

# アプリのコンテキストパス（URLの一部になります）
server.servlet.context-path=/5_3_spring